# SERVE IP
IP = "0.0.0.0"

#SERVE SSL PORT
SSL_PORT = 9900

#SERVE PORT (debug only, do not use on production)
PORT = 9800

#MAX SESSIONS COUNT
MAX_SESSIONS = 30

#MAX SESSION CLIENTS COUNT
MAX_SESSION_CLIENTS = 5

#INACTIVE SESSION TIMEOUT (seconds)
INACTIVE_SESSION_TIMEOUT = 3600

#INACTIVE CLIENT TIMEOUT (no noop activity, etc.) (seconds)
INACTIVE_CLIENT_TIMEOUT = 300

#REDIS IP
REDIS_IP = "127.0.0.1"

#REDIS PORT
REDIS_PORT = 6379